### ISSUE TITLE
flutter error

### ISSUE THREAD

**Issue by dqilu** [instantiations/es_compression#20]
Invalid argument(s): Failed to load dynamic library (dlopen failed: library "eslz4-android64.so" not found)
NoSuchMethodError: The getter 'lz4VersionNumber' was called on null.

**Comment by sethloco** [comment]
Hello,

Thanks for the report.
I just want to make sure I understand the situation.
This dart package comes with pre-compiled binaries for windows/linux/mac.

Android shared libraries currently must be provided by the user.
[This build tool](https://github.com/instantiations/es_compression/blob/master/tool/blob_builder/CMakeLists.txt) can be used to help you do that.

Is your situation that you didn't build a shared library?
Or is it that you have built a shared lz4 library, but you are not able to have the dart package successfully locate it?

**Comment by dqilu** [comment]
I can't build a shared lz4 library.
Can you help me build an Android shared library?
thank you!

**Comment by sethloco** [comment]
Hello,
After the (US) holidays, I will resurrect the Android build I did and create some instructions.  I believe it was Windows/MinGW/Ninja based.
I’ll try and find a good place to put a sample dll to try, as well

**Comment by isong0623** [comment]
Hey bro, see https://github.com/isong0623/android_lib_es_compression0_9_9 @dqilu

**Comment by sethloco** [comment]
@isong0623 These are really great instructions...thank you for putting this together!
I'm mostly a desktop/server dev, and will soon be getting heavier into the mobile/web side of things...so this was really helpful to look at.
If you are interested and think what you put together could be included in es_compression examples...let me know.

**Comment by sethloco** [comment]
Hi @dqilu

@isong0623 provided an android generator for the libs which has been merged into the examples dir of this project.
You can do a pull of the latest and follow the README here:
https://github.com/instantiations/es_compression/blob/master/example/android_jniLibs_generate/README.md
