### ISSUE TITLE
Excuse me, does not support the flutter ios application？

### ISSUE THREAD

**Issue by superwei629** [instantiations/es_compression#24]
use zstd encryption then program output "unsupported platform"

**Comment by sethloco** [comment]
Hello. Thanks for reporting.

Technically it should support ios.  Thanks to a recent contribution, I can confirm that it supports Android.
I don't currently have an ios development platform, but I did see why you might get the 'unsupport platorm' exception and made a correction to the codebase.

I've uploaded 2.0.2 to pubdev.  Give that a try first, and then let me know how it goes.

**Comment by superwei629** [comment]
Thank you for your answer, the simple test pass, but I am a production environment, so to replace other plug-ins

**Comment by sethloco** [comment]
Hello,
Ok, so is there any additional help I can provide at the moment regarding this case?

**Comment by superwei629** [comment]
thank you
Temporarily not, there is need to contact you again, thank you very much
