### ISSUE TITLE
how to decompress data from websocket in streambuilder?

### ISSUE THREAD

**Issue by NeverlandForKi** [instantiations/es_compression#26]
websocket connected success, and received data, snapshot.data like [31, 42, 42,12.......] data is compressed by zstd, how to decompress it?

     
       channel = new IOWebSocketChannel.connect('ws://$SOCKET_URL?token=$userToken');

       // socket connected success

       StreamBuilder(
          stream: channel.stream,
          builder: (context, snapshot) {
          
          print(snapshot.data);  // recieved data [31, 42, 42,12.......]

          final result = compress(snapshot.data);  // here how to compress

          return new Padding(
            child: new Text(''),
          );
        },
      )

**Comment by sethloco** [comment]
Hello,

Have you looked at and run the [Zstd Example](https://github.com/instantiations/es_compression/blob/master/example/zstd_example.dart)?

Something like:
```
import 'package:es_compression/zstd.dart';
final codec = ZstdCodec();
var decoded = codec.decode(snapshot.data);
```

**Comment by NeverlandForKi** [comment]
> Hello,
> 
> Have you looked at and run the [Zstd Example](https://github.com/instantiations/es_compression/blob/master/example/zstd_example.dart)?
> 
> Something like:
> 
> ```
> import 'package:es_compression/zstd.dart';
> final codec = ZstdCodec();
> var decoded = codec.decode(snapshot.data);
> ```

Hello, I tried this, but got error:

The following ArgumentError was thrown building StreamBuilder<dynamic>(dirty, state:
_StreamBuilderBaseState<dynamic, AsyncSnapshot<dynamic>>#1c5bf):
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, ZSTD_compressBound): symbol not
found)

**Comment by sethloco** [comment]
Hello,

What platform are you running this on?

This package includes "ready-to-use prebuilt binaries for Win/Linux/Mac."

A contributor provided an [Android solution here](https://github.com/instantiations/es_compression/tree/master/example/android_jniLibs_generate).

If you can compile zstd sources into the ios project, then it should work but I do not have experience with that.

**Comment by NeverlandForKi** [comment]
@sethloco thanks for reply. I am running this on ios project.  I can complie zstd source into the project, but when I opened the socket page, then got error. Do you know any other method to decompress zstd data?

**Comment by sethloco** [comment]
Hi,

It looks like its an issue with the zstd library that was compiled with the ios project.
Have a look at this, which looks very similar...I see some issues/workarounds related to symbols being stripped on ios which explains the error your getting.  Have a look here...hope it helps.
https://github.com/dart-lang/ffi/issues/41

**Comment by NeverlandForKi** [comment]
hi @sethloco   thank you very much. that helps me a lot

**Comment by sethloco** [comment]
My pleasure.
I'll go ahead and close this for now.
