### ISSUE TITLE
.so files not found on Android release mode

### ISSUE THREAD

**Issue by mejdi14** [instantiations/es_compression#28]
Hey, thanks for the great package, I had the following problem when I tried this package with Android for the first time: 
`Invalid argument(s): Failed to load dynamic library 'eszstd-android32.so': dlopen failed: library "eszstd-android32.so" not found` 
adding the .so files into jniLibs folder fixed the problem when I tried with debug mode and it works perfectly
now when I made a release apk or even when i run on release mode the exact same error appears again like it can't see the files anymore
i have looked inside the apk and all the files are there inside the lib folder
![image](https://user-images.githubusercontent.com/22161913/150870121-5e2bb4b4-1465-459f-b24b-c4884630937b.png)

please let me know I have any idea why this is happening cause I have tried everything
Thanks again

**Comment by mejdi14** [comment]
here is my app gradle code:
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '2'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31
    buildToolsVersion("30.0.3")

    lintOptions {
        disable 'InvalidPackage'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.company.example"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName

    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
        }
    }


    sourceSets {
        main {
            jniLibs.srcDirs = ['jniLibs']
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.5.0-beta01'
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
}
`

and here is where i puted the .so files:
![image](https://user-images.githubusercontent.com/22161913/150870733-25eb89dc-996a-4b72-8c9c-cdfbec0a5c5d.png)

**Comment by mejdi14** [comment]
for anyone having the same issue, gradle requires that the .so file name should start with 'lib' for some reason, just submited a pr which does that for android:
https://github.com/instantiations/es_compression/pull/29

**Comment by sethloco** [comment]
This has been addressed in release v2.0.4.
Thank you again for the contribution
