### ISSUE TITLE
how to use it on the web platform?

### ISSUE THREAD

**Issue by rty813** [instantiations/es_compression#32]
my code:
```
final codec = Lz4Codec();
points = codec.decode(data);
```

and throws exception: `Unsupported operation: No Decoder Implementation`

**Comment by sethloco** [comment]
This project provides:
1. Framework for writing encoder/decoders
2. FFI implementations for lz4, zstd and brotli

This project does NOT currently provide:
1. Pure-Dart implementations of lz4, zstd or brotli

So an lz4 decoder written in pure-dart (i.e no platform ffi to a c library) would need to be developed to satisfy what you are asking for.

Hope this helps and let me know if you have additional questions
