### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'LZ4_versionNumber': dlsym(RTLD_DEFAULT, LZ4_versionNumber): symbol not found

### ISSUE THREAD

**Issue by huangjian0414** [instantiations/es_compression#34]
Can you decompress? IOS

**Comment by sethloco** [comment]
Based on other issues it seems like others are able to use this library in an iOS context.
The latest release has a fix from an iOS user.

A symbol not being found point more towards the native shared library not exporting the functions correctly and so they are not visible from es_compression when attempting an FFI binding.

I don't use this library in a mobile context so I can't be of much assistance for Android/iOS
