### ISSUE TITLE
library for iOS (flutter)

### ISSUE THREAD

**Issue by fuyunmanbu** [instantiations/es_compression#35]
Invalid argument(s): Failed to lookup symbol 'BrotliDecoderCreateInstance': dlsym(RTLD_DEFAULT, BrotliDecoderCreateInstance): symbol not found

this library does not support iOS operations. An error was reported. I don't know if Android is the same.
so，What should I do to solve this problem? Do you have a plan?
It looks great and should support more platforms.

**Comment by sethloco** [comment]
Hello,

The project provides prebuilt shared libraries for Windows/Linux/Mac as stated in the project description.
However, others have contributed to the project to ensure it works for android/ios and I will continue to accept pull-requests for those contexts.

I'm assuming you built the native shared libraries for brotli on ios?  If not, then that is the issue here.

**Comment by fuyunmanbu** [comment]
Hello,
Use `blob_builder` operation failed and the native shared library could not be established. What is wrong with my operation?
Try `mkdir build && cd build`, and then `cmake..`, `make`. The native shared library cannot be created. Do you have detailed steps? My device is Mac, MacOS Monterey 12.3. I'm not very skilled in this. Sorry.

**Comment by sethloco** [comment]
You need to provide the complete output of your cmake build command and your make command for me to try and help identify your issue.

Btw, I’m not sure how to build on ios.  A contributor provided what was necessary to build on Android in the examples section.

Also, the native mac library that ships with es_compression is built in Intel/Mac, not M1/Mac

**Comment by fuyunmanbu** [comment]
What is included in building a local shared library and how should it be used? I can only create `dylib` and `.a` files through the zstd library, not through `blob_builder`

**Comment by fuyunmanbu** [comment]
Do you plan to make it support more platforms?

**Comment by sethloco** [comment]
Hello,

_Background:_
This project was created with 2 goals in mind:
1. General framework for writing compressors (native or pure dart)
2. Pre-built FFI implementations for Windows/Linux/Mac (Intel) as my development platforms are server-side.

_Project Lifecycle:_
- Every time a new version of brotli, lz4 and zstd come out, I rebuild this project with the updated prebuilt shared libraries that are distributed with this package using the instructions at the top of the CMakeLists.txt file in the [blob_builder](https://github.com/instantiations/es_compression/tree/master/tool/blob_builder).
- I accept pull requests and fixes for those interested in running FFI implementations on Android, as seen in pr #22 and pr #29 
- I accept pull requests and fixes for those interested in running FFI implementations on ios, as seen in pr #33 which was in the lastest release.
- If anyone wants to create pure dart implementations of lz4, brotli, zstd...I would also accept those.

_"Do you plan to make it support more platforms?"_

**Mobile**
Based on the pull requests I described above...I can only assume that this package runs on Android and ios.  It just sounds like it requires a specific way of building the shared libraries that you are not able to work out just yet.  I know Android works for sure as I've done that in an emulator before.  And based on pr #33, sounds like it works for ios too.

**Web**
This requires pure dart implementations.  I think it's interesting but don't have the time to do this work.  As stated, I am happy to accept contributions for those.

_"What is included in building a local shared library and how should it be used?"_
These instructions I use to build on Win/Linux/Mac are at the top of the [CMakeLists.txt](https://github.com/instantiations/es_compression/tree/master/tool/blob_builder/CMakeLists.txt)

**Comment by fuyunmanbu** [comment]
Thank you for taking such a long time to discuss this problem

**Comment by sethloco** [comment]
You're very welcome
