### ISSUE TITLE
 Enable to load library in android (flutter).

### ISSUE THREAD

**Issue by santoshyadav140293** [instantiations/es_compression#38]
Hi,

I have used the following dart code to use es_compression .

final codec = BrotliCodec();
bytesStream = asStream(bytes);
bytesStream
  .transform(codec.encoder)
  .transform(codec.decoder)
  .fold<List<int>>(<int>[], (buffer, data) {
    buffer.addAll(data);
    return buffer;
  }).then((decoded) {
    assert(bytes == decoded)
  });

but when i build project it gives following error.
Failed to load dynamic library 'libeslz4.android32.so': dlopen failed : library "libeslz4.android32.so" not found.

Please suggest any solution to load ".so" library using android emulator.

**Comment by sethloco** [comment]
Hello.

Sorry, I don't use mobile contexts, only server-side.
However, there was a contributor who added android jni examples in case that helps
[android_jniLibs_generate](https://github.com/instantiations/es_compression/tree/master/example/android_jniLibs_generate)
