### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast (version 2.0.9)

### ISSUE THREAD

**Issue by chan150** [instantiations/es_compression#40]
Command:
$ escompress -i"input.txt" -o"output.lz4"

Error message:
```
type 'Null' is not a subtype of type 'String' in type cast
#0      main (file:///home/xxx/.pub-cache/hosted/pub.dev/es_compression-2.0.9/bin/es_compress.dart:57:40)
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

Env:
Tested on both `Windows 10`  and `Ubuntu`
`Dart SDK version: 2.19.2 (stable) (Unknown timestamp) on "linux_x64"`
`es_compression-2.0.9`

**Comment by sethloco** [comment]
Pushed 2.0.10 to pub.dev.
Please try again and let me know if everything work for you.

**Comment by chan150** [comment]
@sethloco 
It works for me.
Thanks!
