### ISSUE TITLE
Are there have some examples about ios immplements?

### ISSUE THREAD

**Issue by yongjieYuan** [instantiations/es_compression#41]
Hello, I am developing a Flutter app and I just want to use lz4 to decompress a large amount of data, that's all.
I have checked the issues in the repository and would like to ask you again if anyone has implemented integration with iOS or if there are any examples that can be provided as a reference.

As far as I can see, there are already examples of integration with Android.

**Comment by sethloco** [comment]
Hello,

Based on #33, I'm assuming it was integrated with iOS.  Perhaps reach out to that user? 

The android integration example was provided by a contributor.  I'm happy to do the same for anyone that has an iOS integration example.
