### ISSUE TITLE
 Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libesbrotli-android64.so': dlopen failed: library "libesbrotli-android64.so" not found

### ISSUE THREAD

**Issue by karamatpkid** [instantiations/es_compression#44]
i have pub get this package. i want to compress list<int>/bytes data
` List<int> compressedBytes = brotli.encode(bytes);`
i got below error
I/ViewRootImpl@f09b504[MainActivity](10294): MSG_WINDOW_FOCUS_CHANGED 1 0
I/ViewRootImpl@f09b504[MainActivity](10294): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007a36422000}
D/InputMethodManager(10294): startInputInner - Id : 0
I/InputMethodManager(10294): startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@f09b504[MainActivity](10294): ViewPostIme pointer 0
I/ViewRootImpl@f09b504[MainActivity](10294): ViewPostIme pointer 1
E/flutter (10294): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libesbrotli-android64.so': dlopen failed: library "libesbrotli-android64.so" not found
E/flutter (10294): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (10294): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (10294): #2      OpenLibraryStrategy.open (package:es_compression/src/framework/native/library/open_library_strategy.dart:38:28)
E/flutter (10294): #3      OpenViaOsResolutionStrategy.openFor (package:es_compression/src/framework/native/library/os_resolution_strategy.dart:26:12)
E/flutter (10294): #4      OpenLibrary.openLibrary (package:es_compression/src/framework/native/library/open_library.dart:44:32)
E/flutter (10294): #5      new BrotliLibrary._ (package:es_compression/src/brotli/ffi/library.dart:56:20)
E/flutter (10294): #6      BrotliLibrary._instance (package:es_compression/src/brotli/ffi/library.dart:36:21)
E/flutter (10294): #7      BrotliLibrary._instance (package:es_compression/src/brotli/ffi/library.dart)
E/flutter (10294): #8      new BrotliLibrary (package:es_compression/src/brotli/ffi/library.dart:51:30)
E/flutter (10294): #9      new BrotliDispatcher (package:es_compression/src/brotli/ffi/dispatcher.dart:65:34)
E/flutter (10294): #10     new BrotliCompressFilter (package:es_compression/src/brotli/ffi/compress_filter.dart:20:40)
E/flutter (10294): #11     _makeBrotliCompressFilter (package:es_compression/src/brotli/encoder.dart:178:5)
E/flutter (10294): #12     new _BrotliEncoderSink._ (package:es_compression/src/brotli/encoder.dart:147:13)
E/flutter (10294): #13     BrotliEncoder.startChunkedConversion (package:es_compression/src/brotli/encoder.dart:114:31)
E/flutter (10294): #14     CodecConverter.convert (package:es_compression/src/framework/converters.dart:20:7)
E/flutter (10294): #15     Codec.encode (dart:convert/codec.dart:21:32)
E/flutter (10294): #16     MergePDFFileController.CompressPDf (package:choicepdfeditor/controllers/MergePDFController.dart:120:40)
E/flutter (10294): <asynchronous suspension>

**Comment by sethloco** [comment]
Sorry, I use this server side, not in a mobile context so I don't know where to tell you to put these libraries.

Another user provided an example of building this on Android that may be helpful to you:
https://github.com/instantiations/es_compression/tree/master/example/android_jniLibs_generate
