### ISSUE TITLE
It is recommended to add the prefix `lib` to macos dylib

### ISSUE THREAD

**Issue by MegatronKing** [instantiations/es_compression#45]
I added the `esbrotli-mac64.dylib` in Pod file
```
s.vendored_libraries = 'esbrotli-mac64.dylib'
```
The following error will throw when building
```
ld: library not found for -lesbrotli-mac64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
But `libesbrotli-mac64.dylib` is working.

**Comment by sethloco** [comment]
Will make these adjustments when the project is updated to use Mac/Arm64.  Thank you
