### ISSUE TITLE
我的项目运行的时候报: Failed to load dynamic library 'libeszstd-android64.so': dlopen failed: library "libeszstd-android64.so" not found

### ISSUE THREAD

**Issue by zhangyuankai** [instantiations/es_compression#46]
请问这个so文件从哪里获得

**Comment by huangbos** [comment]
我也遇到了,这个怎么解决呢?

**Comment by ddomnik** [comment]
Same issue on Windows:
` Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'eslz4-win64.dll': The specified module could not be found.`
