### ISSUE TITLE
Unhandled Exception: FormatException: ERROR_frameType_unknown

### ISSUE THREAD

**Issue by riccardo-runci** [instantiations/es_compression#48]
Hello, i'm trying to decompress .pak file, but i'm getting this error

Unhandled Exception: FormatException: ERROR_frameType_unknown

```var decompressedData = Lz4Codec().decode(pakBytes);```

**Comment by sethloco** [comment]
I don’t know much about .pak files, but a cursory look shows that it’s an archive file format (like rar or zip).  This library doesn’t read pak files.

If the pak archive contains lz4 compressed data, then a program that reads pak files would need to tell the lz4 decoder the correct offset into the pak file.  This is outside the scope of this library

**Comment by riccardo-runci** [comment]
> I don’t know much about .pak files, but a cursory look shows that it’s an archive file format (like rar or zip). This library doesn’t read pak files.
> 
> If the pak archive contains lz4 compressed data, then a program that reads pak files would need to tell the lz4 decoder the correct offset into the pak file. This is outside the scope of this library

what i'm trying to achieve is a dart app like this
https://github.com/Norbyte/lslib/tree/master
that can unzip .pak files, maybe it use lz4 compression

**Comment by sethloco** [comment]
Similar to a zip file being composed of entries (files) that use gzip compression, It seems like a pak file is composed of 1 or more entries that may be lz4 compressed.  

So Im guessing you need a pak reader to read the “entries”.  And each entry could be read with an lz4 decoder.

Just a guess

**Comment by riccardo-runci** [comment]
> Similar to a zip file being composed of entries (files) that use gzip compression, It seems like a pak file is composed of 1 or more entries that may be lz4 compressed.
> 
> So Im guessing you need a pak reader to read the “entries”. And each entry could be read with an lz4 decoder.
> 
> Just a guess

Thanks for your suggestion, tonight i can upload a sample file just if you need for testing
