### ISSUE TITLE
import 'dart:cli' breaks on Dart 3.4+

### ISSUE THREAD

**Issue by gmpassos** [instantiations/es_compression#50]
https://github.com/instantiations/es_compression/blob/b74fc799535c905cc4c2add6551fc6077d62cfaf/lib/src/framework/native/library/package_relative_strategy.dart#L1

... totally unnecessary to use `dart:cli` for that:

https://github.com/instantiations/es_compression/blob/b74fc799535c905cc4c2add6551fc6077d62cfaf/lib/src/framework/native/library/package_relative_strategy.dart#L55

**Comment by sethloco** [comment]
Thanks for reporting.  I will review this week how to replace waitFor()

**Comment by gmpassos** [comment]
The biggest problem here is that it's used in constructors, and a substitute will return a Future and require an await, which can't be used in a constructor. You will need to change the calling point to outside the constructors.

**Comment by sethloco** [comment]
This has been fixed in v2.0.12 which is up in pub.dev.
